version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: aquasertao_db
    environment:
      POSTGRES_USER: aquasertao_user
      POSTGRES_PASSWORD: aquasertao_password
      POSTGRES_DB: aquasertao_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: aquasertao_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aquasertao_api
    network_mode: host
    restart: unless-stopped
    depends_on:
      - rabbitmq

  supplier-service:
    build:
      context: ./supplier-service
      dockerfile: Dockerfile
    container_name: aquasertao_supplier
    network_mode: host
    restart: unless-stopped
    depends_on:
      - rabbitmq

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: aquasertao_gateway
    network_mode: host
    restart: unless-stopped
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
