spring:
  application:
    name: aquasertao-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-cool-glitter-ap8z1vk7.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_ZWCyu4sKU6gE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    listener:
      type: simple
      simple:
        auto-startup: false

server:
  port: 8081
  max-http-request-header-size: 10MB
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}

google:
  client-id: ${GOOGLE_CLIENT_ID:60186836539-9ouq8mu9mn7ulcl0qjucioefc4gqthtt.apps.googleusercontent.com}
